config/routes.rb
IVote::Application.routes.draw do
  resources :settings
  
  devise_for :proxies

  get "users/index"

  get "voting/index"

  post "voting/vote"

  get "voting/confirm"
  
  match "voting/quickpick" => 'voting#quickpick'
  
  post "voting/quickvote"

  resources :candidates

  devise_for :users

  get "public/index"
  
  match 'admin/tally' => 'admin#tally'
  
  get 'admin/advance'
  
  get 'admin/wipe'
  
  get 'elections/election'
  
  post 'elections/vote'
  
  root :to => 'public#index'
  
  get 'admin/irv_tally'
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
  match 'users/assign_proxy' => 'users#assign_proxy'
  
  post 'users/proxy_assign'

  resources :users
  
  resources :proxies

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  attr_accessible :image_url, :name, :picture
  
  has_attached_file :picture
  
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_filter :require_login
  

   def require_admin
     unless current_user.admin?
       logger.info "tried to access restricted area"
       redirect_to "/"
     end
   end
  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidates }
    end
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/new
  # GET /candidates/new.json
  def new
    @candidate = Candidate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/1/edit
  def edit
    @candidate = Candidate.find(params[:id])
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(params[:candidate])
    @candidate.yes = 0
    @candidate.no = 0
    @candidate.abstain = 0
    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render json: @candidate, status: :created, location: @candidate }
      else
        format.html { render action: "new" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /candidates/1
  # PUT /candidates/1.json
  def update
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      if @candidate.update_attributes(params[:candidate])
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to candidates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for @candidate, :html => {:multipart => true} do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <!--div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div-->
	<div class="field">
	<%= f.label :picture %>
	<%= f.file_field :picture%>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<h1>Listing candidates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Image url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @candidates.each do |candidate| %>
  <tr>
    <td><%= candidate.name %></td>
    <td><%= candidate.image_url %></td>
    <td><%= link_to 'Show', candidate %></td>
    <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
    <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>New candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @candidate.name %>
</p>

<p>
  <b>Image url:</b>
  <%= @candidate.picture.url%>
</p>

<p>
	<b>Image:</b>
	<%= image_tag(@candidate.picture.url,  :class => "candidate_image")%>
	</p>


<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>