config/routes.rb
IVote::Application.routes.draw do
  resources :settings
  
  devise_for :proxies

  get "users/index"

  get "voting/index"

  post "voting/vote"

  get "voting/confirm"
  
  match "voting/quickpick" => 'voting#quickpick'
  
  post "voting/quickvote"

  resources :candidates

  devise_for :users

  get "public/index"
  
  match 'admin/tally' => 'admin#tally'
  
  get 'admin/advance'
  
  get 'admin/wipe'
  
  get 'elections/election'
  
  post 'elections/vote'
  
  root :to => 'public#index'
  
  get 'admin/irv_tally'
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
  match 'users/assign_proxy' => 'users#assign_proxy'
  
  post 'users/proxy_assign'

  resources :users
  
  resources :proxies

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "iVote" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels >
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels >
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels >
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels >
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">iVote</a>
          <div class="nav-collapse">
            <ul class="nav">
			<% if current_user || current_proxy %>
              <li><%= link_to "Voting", "/voting/index"  %></li>
				<% if current_user && current_user.admin? %>
              <li><%= link_to "Candidates", "/candidates"  %></li>
				<% end %>
				<%end%>
			<% if current_user%>
			    <li><a href="#">Signed in as <%= current_user.name %></a></li>
			    <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
				<% elsif current_proxy %>
				<li><a href="#">Signed in as <%= current_proxy.email%></a></li>
					<li><%= link_to "Sign out", destroy_proxy_session_path, id: "sign_out", method: "delete"%>
			  <% else %>
			   <li> <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></li>
				<li> <%= link_to "Sign In With Email", "/proxies/sign_in", id: "sign_in"%>
			  <% end %>
			
			
			
			
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container">
	<% if current_proxy%>
	<div class="page-header">
		<h1>This is a proxy vote<small>(Or otherwise you don't have facebook)</small></h1>
	</div>
	<% end%>
  
              <%= yield %>

            
    
  

      <footer>
        <p>&copy; Scottie Biddle on behalf of Tau Gamma Chapter of Theta Tau Professional Engineering Fraternity 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>